<a href="https://colab.research.google.com/github/srj3777/Python/blob/main/Basic%20Pandas%20and%20Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import pandas as pd

# ------------------------------------------------------------
# 1. Load CSV and Saving to CSV
# ------------------------------------------------------------
df = pd.read_csv("/content/drive/MyDrive/LAB/random_marks.csv")
print(df)


               Name Python  JAVA  NET     C ANGULAR
0        Mike Brown     97    93   19   35%      27
1    Laura Martinez     96    47   79     3      55
2      Laura Garcia    NaN  $55   23@    41      97
3      Jane Johnson    *23    32   70    84      72
4       Katie Brown     9%    80   75   37$      35
5     Mike Williams     96    91   88   7@2      76
6      Sophia Davis     34   8@1    0    73      0%
7     Alex Martinez     23    73   60   5$3      73
8       David Davis     48     6    6  $90       60
9    Mike Hernandez    1%4   @23   99    87       0
10   Chris Williams     98     0  79%    62       3
11      Katie Davis     91   80%    2    82      64
12       Mike Jones     63   37%  NaN    49      47
13   Chris Martinez     *1    41   40   *35     NaN
14  Chris Hernandez     37    83   93   2$7      60
15   Katie Martinez     10    86   64    43      72
16      John Garcia     88    99   60  $77      *85
17     Emily Garcia    *83    34  1%1    35      33
18      Kati

In [22]:
# ------------------------------------------------------------
# 2. Explore Data
# ------------------------------------------------------------

print(df.shape)
print(df.columns)
display(df.head())
display(df.tail())
display(df.head(3))
df.sample()

df.info()
df.describe()

print(df)



(20, 6)
Index(['Name', 'Python', 'JAVA', 'NET', 'C', 'ANGULAR'], dtype='object')


Name Python  JAVA  NET    C ANGULAR
0      Mike Brown     97    93   19  35%      27
1  Laura Martinez     96    47   79    3      55
2    Laura Garcia    NaN  $55   23@   41      97
3    Jane Johnson    *23    32   70   84      72
4     Katie Brown     9%    80   75  37$      35

Name Python JAVA  NET     C ANGULAR
15  Katie Martinez     10   86   64    43      72
16     John Garcia     88   99   60  $77      *85
17    Emily Garcia    *83   34  1%1    35      33
18     Katie Jones     44  50*  2*8   14#      55
19      John Brown     11   53   62    59      91

Name Python  JAVA  NET    C ANGULAR
0      Mike Brown     97    93   19  35%      27
1  Laura Martinez     96    47   79    3      55
2    Laura Garcia    NaN  $55   23@   41      97

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Name     20 non-null     object
 1   Python   19 non-null     object
 2   JAVA     20 non-null     object
 3   NET      19 non-null     object
 4   C        20 non-null     object
 5   ANGULAR  19 non-null     object
dtypes: object(6)
memory usage: 1.1+ KB
               Name Python  JAVA  NET     C ANGULAR
0        Mike Brown     97    93   19   35%      27
1    Laura Martinez     96    47   79     3      55
2      Laura Garcia    NaN  $55   23@    41      97
3      Jane Johnson    *23    32   70    84      72
4       Katie Brown     9%    80   75   37$      35
5     Mike Williams     96    91   88   7@2      76
6      Sophia Davis     34   8@1    0    73      0%
7     Alex Martinez     23    73   60   5$3      73
8       David Davis     48     6    6  $90       60
9    Mike Hernandez    1%4   @23   99    8

In [23]:
# 3. Clean Special Characters in Marks
# ------------------------------------------------------------
mark_columns = ["Python", "JAVA", "NET", "C", "ANGULAR"]

for col in mark_columns:
    df[col] = df[col].astype(str).str.replace(r'[^0-9]', '', regex=True)
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.head()


Name  Python  JAVA   NET   C  ANGULAR
0      Mike Brown    97.0    93  19.0  35     27.0
1  Laura Martinez    96.0    47  79.0   3     55.0
2    Laura Garcia     NaN    55  23.0  41     97.0
3    Jane Johnson    23.0    32  70.0  84     72.0
4     Katie Brown     9.0    80  75.0  37     35.0

In [24]:
# ------------------------------------------------------------
# 4. Handle Missing Values
# ------------------------------------------------------------
df.isna().sum()
df.fillna(0, inplace=True)
df.head()


Name  Python  JAVA   NET   C  ANGULAR
0      Mike Brown    97.0    93  19.0  35     27.0
1  Laura Martinez    96.0    47  79.0   3     55.0
2    Laura Garcia     0.0    55  23.0  41     97.0
3    Jane Johnson    23.0    32  70.0  84     72.0
4     Katie Brown     9.0    80  75.0  37     35.0

In [25]:
# ------------------------------------------------------------
# 4. Adding New Column to df
# ------------------------------------------------------------

df["RUBY"]=df["JAVA"]+df["C"]
df

Name  Python  JAVA   NET   C  ANGULAR  RUBY
0        Mike Brown    97.0    93  19.0  35     27.0   128
1    Laura Martinez    96.0    47  79.0   3     55.0    50
2      Laura Garcia     0.0    55  23.0  41     97.0    96
3      Jane Johnson    23.0    32  70.0  84     72.0   116
4       Katie Brown     9.0    80  75.0  37     35.0   117
5     Mike Williams    96.0    91  88.0  72     76.0   163
6      Sophia Davis    34.0    81   0.0  73      0.0   154
7     Alex Martinez    23.0    73  60.0  53     73.0   126
8       David Davis    48.0     6   6.0  90     60.0    96
9    Mike Hernandez    14.0    23  99.0  87      0.0   110
10   Chris Williams    98.0     0  79.0  62      3.0    62
11      Katie Davis    91.0    80   2.0  82     64.0   162
12       Mike Jones    63.0    37   0.0  49     47.0    86
13   Chris Martinez     1.0    41  40.0  35      0.0    76
14  Chris Hernandez    37.0    83  93.0  27     60.0   110
15   Katie Martinez    10.0    86  64.0  43     72.0   129
16      John Garcia    88.0    99  60.0  77     85.0   176
17     Emily Garcia    83.0    34  11.0  35     33.0    69
18      Katie Jones    44.0    50  28.0  14     55.0    64
19       John Brown    11.0    53  62.0  59     91.0   112

In [26]:
# 5. Add Total & Average Columns
# ------------------------------------------------------------
df["Total"] = df[mark_columns].sum(axis=1)
df["Average"] = df[mark_columns].mean(axis=1)

df.head()


Name  Python  JAVA   NET   C  ANGULAR  RUBY  Total  Average
0      Mike Brown    97.0    93  19.0  35     27.0   128  271.0     54.2
1  Laura Martinez    96.0    47  79.0   3     55.0    50  280.0     56.0
2    Laura Garcia     0.0    55  23.0  41     97.0    96  216.0     43.2
3    Jane Johnson    23.0    32  70.0  84     72.0   116  281.0     56.2
4     Katie Brown     9.0    80  75.0  37     35.0   117  236.0     47.2

In [56]:
# 6. Filtering Examples
# ------------------------------------------------------------

print(df.isin({'Name':['David Davis']}))
print(df[df["Python"] > 50])
print(df[df["JAVA"] == 0])
print(df[(df["NET"] > 40) & (df["ANGULAR"] < 60)])
df.query("C > 70")
df.loc[df['Name'].str.contains('Katie Brown', case=False, na=False)]
df.iloc[1]
pd.unique(df["Name"])


     Name  Python   JAVA    NET      C  ANGULAR   RUBY  Total  Average
0   False   False  False  False  False    False  False  False    False
1   False   False  False  False  False    False  False  False    False
2   False   False  False  False  False    False  False  False    False
3   False   False  False  False  False    False  False  False    False
4   False   False  False  False  False    False  False  False    False
5   False   False  False  False  False    False  False  False    False
6   False   False  False  False  False    False  False  False    False
7   False   False  False  False  False    False  False  False    False
8    True   False  False  False  False    False  False  False    False
9   False   False  False  False  False    False  False  False    False
10  False   False  False  False  False    False  False  False    False
11  False   False  False  False  False    False  False  False    False
12  False   False  False  False  False    False  False  False    False
13  Fa

array(['Mike Brown', 'Laura Martinez', 'Laura Garcia', 'Jane Johnson',
       'Katie Brown', 'Mike Williams', 'Sophia Davis', 'Alex Martinez',
       'David Davis', 'Mike Hernandez', 'Chris Williams', 'Katie Davis',
       'Mike Jones', 'Chris Martinez', 'Chris Hernandez',
       'Katie Martinez', 'John Garcia', 'Emily Garcia', 'Katie Jones',
       'John Brown'], dtype=object)

In [34]:
# 7. Sorting Examples
# ------------------------------------------------------------
df.sort_values(by="Total", ascending=False).head(3)
df.sort_values(by=["Python", "JAVA"], ascending=[False, True]).head()


Name  Python  JAVA   NET   C  ANGULAR  RUBY  Total  Average
10  Chris Williams    98.0     0  79.0  62      3.0    62  242.0     48.4
0       Mike Brown    97.0    93  19.0  35     27.0   128  271.0     54.2
1   Laura Martinez    96.0    47  79.0   3     55.0    50  280.0     56.0
5    Mike Williams    96.0    91  88.0  72     76.0   163  423.0     84.6
11     Katie Davis    91.0    80   2.0  82     64.0   162  319.0     63.8

In [35]:
# 8. Save Cleaned CSV
# ------------------------------------------------------------
df.to_csv("cleaned_marks.csv", index=False)
print("Cleaned CSV saved as cleaned_marks.csv")



Cleaned CSV saved as cleaned_marks.csv


In [50]:
import numpy as np
# 1. NumPy Operations
# ------------------------------------------------------------
arr = df[mark_columns].to_numpy()
print(arr)
print(arr.ndim)
print(arr.size)
#
mean_vals = np.mean(arr, axis=0)
print(mean_vals)
print(np.max(arr, axis=0))
print(np.min(arr, axis=0))
print(np.sum(arr, axis=0))


print(arr.shape)
print(arr.reshape(5, 20))
print(arr.flatten())#same as arr.reshape(-1)
# slicing
print(arr[1:5])
print(arr[::-1])




[[97. 93. 19. 35. 27.]
 [96. 47. 79.  3. 55.]
 [ 0. 55. 23. 41. 97.]
 [23. 32. 70. 84. 72.]
 [ 9. 80. 75. 37. 35.]
 [96. 91. 88. 72. 76.]
 [34. 81.  0. 73.  0.]
 [23. 73. 60. 53. 73.]
 [48.  6.  6. 90. 60.]
 [14. 23. 99. 87.  0.]
 [98.  0. 79. 62.  3.]
 [91. 80.  2. 82. 64.]
 [63. 37.  0. 49. 47.]
 [ 1. 41. 40. 35.  0.]
 [37. 83. 93. 27. 60.]
 [10. 86. 64. 43. 72.]
 [88. 99. 60. 77. 85.]
 [83. 34. 11. 35. 33.]
 [44. 50. 28. 14. 55.]
 [11. 53. 62. 59. 91.]]
2
100
[48.3  57.2  47.9  52.9  50.25]
[98. 99. 99. 90. 97.]
[0. 0. 0. 3. 0.]
[ 966. 1144.  958. 1058. 1005.]
(20, 5)
[[97. 93. 19. 35. 27. 96. 47. 79.  3. 55.  0. 55. 23. 41. 97. 23. 32. 70.
  84. 72.]
 [ 9. 80. 75. 37. 35. 96. 91. 88. 72. 76. 34. 81.  0. 73.  0. 23. 73. 60.
  53. 73.]
 [48.  6.  6. 90. 60. 14. 23. 99. 87.  0. 98.  0. 79. 62.  3. 91. 80.  2.
  82. 64.]
 [63. 37.  0. 49. 47.  1. 41. 40. 35.  0. 37. 83. 93. 27. 60. 10. 86. 64.
  43. 72.]
 [88. 99. 60. 77. 85. 83. 34. 11. 35. 33. 44. 50. 28. 14. 55. 11. 53. 62.
  59. 91

In [59]:
# 2. NumPy Random and different dimension
# ------------------------------------------------------------
x1 = np.random.random((2, 5)) ##generate 2 dimension
print(x1)
y1=np.random.randint(1,10,(2,5))##generte 2 dimension with value range from 1-9
print(y1)

z1=np.random.randint(1,10,(2,2,3))##generte 2 dimension with value range from 1-9
print(z1)

print(z1[1][0][0])
for x in z1: ## lOOPING THROUGH 3 DIMENSION
  for y in x:
    for z in y:
      print(z)


[[0.62030537 0.35590156 0.8272289  0.27168301 0.93573449]
 [0.12746355 0.57508884 0.10332879 0.53998849 0.4175011 ]]
[[3 8 4 4 9]
 [3 5 3 6 3]]
[[[4 1 8]
  [6 2 1]]

 [[9 3 2]
  [3 6 7]]]
9
4
1
8
6
2
1
9
3
2
3
6
7
